### ISSUE TITLE
Image Browser is not displayed

### ISSUE THREAD

**Issue by stickyhands** [froala/KMSFroalaEditorBundle#19]
![capture d ecran 2016-06-02 a 16 42 10](https://cloud.githubusercontent.com/assets/2256150/15748981/1600fa20-28e1-11e6-9b72-4e0197566ed8.png)

Im loading all the plugins but the image browser is not displayed. Any idea ? (im using dev-master)
image_manager.min.js is loaded and so is image_manager.min.css

**Comment by samarhxc** [comment]
You have to drag and drop your image file, or click on the area to open the file browser.

**Comment by stickyhands** [comment]
well, thats not what I meant, I'm talking about that "Browse": 
![capture d ecran 2016-06-02 a 17 12 11](https://cloud.githubusercontent.com/assets/2256150/15750063/38eeaaec-28e5-11e6-8ea7-3199e3d3456c.png)

**Comment by mufac** [comment]
I think I know what is going on here. The bug is actually with all plugins that have underscores in their names (image_manager is affected but so are others like paragraph_style). The list of plugins is obtained here:

https://github.com/froala/KMSFroalaEditorBundle/blob/master/Form/Type/FroalaEditorType.php#L134

and used to populate the Froala pluginsEnabled config setting. The problem is that while underscores between words in the correct format for generating paths to asset files (JS/CSS), pluginsEnabled expects camelCase plugin names.

The solution is to apply Doctrine\Common\Util\Inflector::camelize() to the array elements before setting $p_view->vars [ "arrOption" ][ "pluginsEnabled" ] on the line referenced above (while still using the original values on lines 135 and 136).

**Comment by samarhxc** [comment]
Good job !
Just fixed and commited, thank you !
