### ISSUE TITLE
Code style/static analysis

### ISSUE THREAD

**Issue by jmsche** [froala/KMSFroalaEditorBundle#91]
Hi @sguionni,

I'm wondering if you're open to a massive code refactor? Here's what I'd like to do:

* Setup phpstan for static analysis
* Setup phpcs (not many rules, eg. enforce spaces instead of tabs, short array syntax...) for code style
* Remove useless comments & rename some parameters (maybe functions too)
* Setup a travis config to make phpstan/phpcs run for PRs

WDYT?

**Comment by sguionni** [comment]
I think it's a good idea, i started this bundle long time ago and i have no time to maintain it anymore, so go ahead!

**Comment by jmsche** [comment]
Thanks, I'll start working on it after the docs update :)

**Comment by AxelBriche** [comment]
Hello, some news? This bundle is ready for the futur? Thanks.

**Comment by jmsche** [comment]
Hello @AxelBriche, code style & static analysis are not done yet, but the bundle works well with last minor of Symfony (5.1).

**Comment by mpoiriert** [comment]
Hi @jmsche The bug https://github.com/froala/KMSFroalaEditorBundle/issues/17 to be fixed will need a renaming of all form type options and will cause a BC.

Doing both at the same time would help. I will fork this project because I need this ASAP for a client. But maybe we can work together to make this more "Symfony" friendly.

**Comment by jmsche** [comment]
Done with 4.0.0 release.
